- hosts: all
  remote_user: vagrant
  tasks:
    - name: Instalar git
      become: true
      apt: name=git state=installed update_cache=true

    - name: Instalar python3 y extras
      become: true
      apt: name={{ item }} state=installed update_cache=true
      with_items:
        - python3
        - python3-setuptools
        - python3-pip

    - name: Actualizar sistema
      become: true
      command: apt update

    - name: Autoremove
      become: true
      command: apt autoremove

    - name: Actualizar pip a la última versión
      command: pip3 install --upgrade pip
