- hosts: twitterlocationflow
  sudo: yes
  remote_user: vagrant

  tasks:
  - name: Actualizar sistema
    command: sudo apt update

  - name: Upgrade sistema
    command: sudo apt upgrade

  - name: Instalar Git
    command: sudo apt-get install -y git

  - name: Instalar pip
    command: sudo apt-get install -y python3-pip

  - name: Instalar requirements
    command: pip3 install -r TwitterLocationFlow/requirements.txt
