- hosts: all
  remote_user: vagrant
  tasks:
    - name: Instalar git
      become: true
      apt: name=git state=installed update_cache=true

    - name: Instalar python3 y extras
      become: true
      apt: name=['python3','python3-setuptools','python3-pip'] state=installed update_cache=yes
      
    - name: Actualizar sistema
      become: true
      command: apt update

    - name: Update pip
      command: pip3 install --upgrade pip

    - name: Install gunicorn
      command: pip install git+https://github.com/benoitc/gunicorn.git
