- hosts: all
  remote_user: vagrant
  vars_files:
    - var.yml
  gather_facts: no
  become: yes
  tasks:
    - name: Instalar paquetes base
      apt: pkg={{ item }} update-cache=yes cache_valid_time=3600
      with_items: "{{ system_packages }}"

    - name: Actualizar sistema
      command: apt update

    - name: Update pip
      command: pip3 install --upgrade pip

    - name: Install gunicorn
      command: pip install git+https://github.com/benoitc/gunicorn.git
